apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 3
  maxReplicaCount: 10
  triggers:
    - type: redis
      metadata:
        address: redis.default.svc.cluster.local:6379
        listName: pdf-queue
        listLength: "5"